# Generated by Django 3.2.4 on 2021-08-02 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamresultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('written_exam', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Total_40', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(40.0)])),
                ('Total_100', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
            options={
                'db_table': 'vote_votingmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='exam_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('choiceA', models.TextField(max_length=1000)),
                ('choiceB', models.TextField(max_length=1000)),
                ('choiceC', models.TextField(max_length=1000)),
                ('choiceD', models.TextField(default='All', max_length=1000)),
                ('choiceE', models.TextField(default='None', max_length=1000)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('User_answer', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
