# Generated by Django 3.2.4 on 2021-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ann_By', models.CharField(max_length=20)),
                ('Ann_Title', models.CharField(max_length=200)),
                ('Ann_Dis', models.TextField(max_length=1000)),
                ('Ann_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
