# Generated by Django 3.2.4 on 2021-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Scheduled_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
