# Generated by Django 3.2.4 on 2021-08-02 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election_Committe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('stat', models.BooleanField(default=False)),
                ('cand1', models.BooleanField(default=False)),
                ('cand2', models.BooleanField(default=False)),
                ('cand3', models.BooleanField(default=False)),
                ('cand4', models.BooleanField(default=False)),
                ('cand5', models.BooleanField(default=False)),
                ('cand6', models.BooleanField(default=False)),
                ('cand7', models.BooleanField(default=False)),
                ('cand8', models.BooleanField(default=False)),
                ('cand9', models.BooleanField(default=False)),
                ('cand10', models.BooleanField(default=False)),
                ('cand11', models.BooleanField(default=False)),
                ('cand12', models.BooleanField(default=False)),
                ('cand13', models.BooleanField(default=False)),
                ('cand14', models.BooleanField(default=False)),
                ('cand15', models.BooleanField(default=False)),
                ('cand16', models.BooleanField(default=False)),
                ('cand17', models.BooleanField(default=False)),
                ('cand18', models.BooleanField(default=False)),
                ('cand19', models.BooleanField(default=False)),
                ('cand20', models.BooleanField(default=False)),
                ('cand21', models.BooleanField(default=False)),
                ('cand22', models.BooleanField(default=False)),
                ('cand23', models.BooleanField(default=False)),
                ('cand24', models.BooleanField(default=False)),
                ('cand25', models.BooleanField(default=False)),
                ('cand26', models.BooleanField(default=False)),
                ('cand27', models.BooleanField(default=False)),
                ('cand28', models.BooleanField(default=False)),
                ('cand29', models.BooleanField(default=False)),
                ('cand30', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'election_committe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'user_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('User_Role', models.CharField(max_length=30)),
                ('User_Status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('stat', models.BooleanField(default=False)),
                ('cand1', models.BooleanField(default=False)),
                ('cand2', models.BooleanField(default=False)),
                ('cand3', models.BooleanField(default=False)),
                ('cand4', models.BooleanField(default=False)),
                ('cand5', models.BooleanField(default=False)),
                ('cand6', models.BooleanField(default=False)),
                ('cand7', models.BooleanField(default=False)),
                ('cand8', models.BooleanField(default=False)),
                ('cand9', models.BooleanField(default=False)),
                ('cand10', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vote_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VotingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('protocol', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('presentation_skill', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(15.0)])),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('strategic_plane', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('answering', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Time_management', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('certifcate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('written_exam', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('oral_interview', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Str_and_opra_plane', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(15.0)])),
                ('Total_40', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(40.0)])),
                ('Total_60', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('Total_100', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
        ),
    ]
