# Generated by Django 3.2.4 on 2021-08-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election_committe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voters',
            options={},
        ),
    ]
