# Generated by Django 3.2.4 on 2021-08-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20210802_1838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='election_committe',
            table=None,
        ),
        migrations.AlterModelTable(
            name='voters',
            table=None,
        ),
    ]
