# Generated by Django 3.2.4 on 2021-08-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainModel',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_by', models.CharField(max_length=20)),
                ('comp_dis', models.TextField(max_length=1000)),
                ('comp_to', models.CharField(choices=[('Admin', 'Admin Group'), ('Committee', 'Election Committee Group')], max_length=50)),
                ('comp_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complain_complainmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_response', models.TextField(max_length=1000)),
                ('response_by', models.CharField(max_length=50)),
                ('response_group', models.CharField(max_length=50)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complain_response1',
                'managed': False,
            },
        ),
    ]
